stages:
  - deploy

deploy_fe:
  stage: deploy
  image: node:latest
  tags:
    - hva
  only:
    refs:
      - master
  #    changes:
  #      - [your-fe-folder-here]/**/*"
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - export RAILWAY_TOKEN=${RAILWAY_TOKEN_FE}
    - cd EWA-vue
    - railway up --service=RAILWAY_FE_Service -d

deploy_be:
  stage: deploy
  image: node:latest
  tags:
    - hva
  only:
    refs:
      - master
  #    changes:
  #      - "[your-be-folder-here]/**/*"
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - export RAILWAY_TOKEN=${RAILWAY_TOKEN_BE}
    - cd EWA-server
    - railway up --service=RAILWAY_BE_Service -d
